### ISSUE TITLE
SSL verification problem in ZMON Scheduler in Vagrant box

### ISSUE THREAD

**Issue by hjacobs** [zalando/zmon#14]
```
Caused by: org.springframework.web.client.ResourceAccessException: I/O error on GET request for "https://localhost:8443/api/v1/checks/all-active-alert-definitions":hostname in certificate didn't match: <localhost> != <unknown>; nested exception is javax.net.ssl.SSLException: hostname in certificate didn't match: <localhost> != <unknown>
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:584)
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:529)
	at org.springframework.web.client.RestTemplate.exchange(RestTemplate.java:447)
	at de.zalando.zmon.scheduler.ng.alerts.DefaultAlertSource.getCollection(DefaultAlertSource.java:84)
	at de.zalando.zmon.scheduler.ng.alerts.AlertRepository.fill(AlertRepository.java:31)
	at de.zalando.zmon.scheduler.ng.alerts.AlertRepository.<init>(AlertRepository.java:67)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:147)
	... 52 more
Caused by: javax.net.ssl.SSLException: hostname in certificate didn't match: <localhost> != <unknown>
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:238)
	at org.apache.http.conn.ssl.BrowserCompatHostnameVerifier.verify(BrowserCompatHostnameVerifier.java:54)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:159)
	at org.apache.http.conn.ssl.AbstractVerifier.verify(AbstractVerifier.java:140)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.verifyHostname(SSLConnectionSocketFactory.java:301)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:291)
	at org.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:259)
	at org.apache.http.impl.conn.HttpClientConnectionOperator.connect(HttpClientConnectionOperator.java:125)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:319)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:363)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:219)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:195)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:86)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:108)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:184)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:82)
	at org.springframework.http.client.HttpComponentsClientHttpRequest.executeInternal(HttpComponentsClientHttpRequest.java:91)
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48)
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:53)
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:568)
	... 62 more

**Comment by hjacobs** [comment]
I suppose we need to generate a new self-signed SSL cert for ZMON Controller on "localhost".

**Comment by hjacobs** [comment]
Fixed in ZMON Controller Docker image cd189 by generating a new self-signed certificate with OpenSSL for "localhost":

* https://github.com/zalando/zmon-controller/commit/72d59c4bfe0030afad4bb1882b9f3f9e75343233
* https://github.com/zalando/zmon-controller/commit/d1e6f7600a00c2d15b4249f92e390e6f8dbf8ac6
