### ISSUE TITLE
ImportError: No module named 'dns.exception'

### ISSUE THREAD

**Issue by mtesseract** [zalando/zmon#26]
Hi,

I have just installed zmon-cli via pip3. It seems to have completed successfully:

[...]
Successfully installed cffi-1.8.3 clickclick-1.2.1 cryptography-1.5.2 dnspython-1.15.0 dnspython3-1.15.0 easydict-1.6 keyring-10.0.2 pycparser-2.16 setuptools-28.6.1 zmon-cli-1.0.57

Running zmon-cli --version fails with the following stack trace:

    $ zmon --version
    Traceback (most recent call last):
      File "/usr/local/bin/zmon", line 7, in <module>
        from zmon_cli.main import main
      File "/usr/local/lib/python3.5/dist-packages/zmon_cli/main.py", line 3, in <module>
        from zmon_cli.cmds import cli
      File "/usr/local/lib/python3.5/dist-packages/zmon_cli/cmds/__init__.py", line 1, in <module>
        from zmon_cli.cmds.command import cli
      File "/usr/local/lib/python3.5/dist-packages/zmon_cli/cmds/command.py", line 10, in <module>
        from zmon_cli.config import DEFAULT_CONFIG_FILE
      File "/usr/local/lib/python3.5/dist-packages/zmon_cli/config.py", line 7, in <module>
        import zign.api
      File "/usr/local/lib/python3.5/dist-packages/zign/api.py", line 5, in <module>
        import stups_cli.config
      File "/usr/local/lib/python3.5/dist-packages/stups_cli/config.py", line 2, in <module>
        import dns.exception
    ImportError: No module named 'dns.exception'

Anything I have done wrong here?

Thanks,
Moritz

**Comment by mohabusama** [comment]
You will need to reinstall `dnspython3`

```bash
pip3 install -U --force-reinstall dnspython3
```

**Comment by mtesseract** [comment]
Thanks, that has solved the issue.

So ist that a missing dependency? Or should that note be added to the manual?

**Comment by mohabusama** [comment]
It is used by a dependency (``zign``), which probably was installed with older version. So, not specifically related to ``zmon-cli``.

**Comment by mtesseract** [comment]
I understand. For me this issue is solved.

But personally I think it would be an improvement to add a note to the manual. Following the manual step by step and beeing greeted with stack traces without any mention of this in the manual does not give the best user experience.
