### ISSUE TITLE
CannotGetJdbcConnectionException: Failed to acquire connection for virtual shard 0 for get_alert_definitions_by_team_and_tag; neste...

### ISSUE THREAD

**Issue by vibhory2j** [zalando/zmon#46]
https://sentry.stups-test.zalan.do/sentry/zmon-controller/issues/154/

```
PSQLException: This connection has been closed.
    at org.postgresql.jdbc2.AbstractJdbc2Connection.checkClosed(AbstractJdbc2Connection.java:843)
    at org.postgresql.jdbc4.Jdbc4Connection.getMetaData(Jdbc4Connection.java:54)
    at com.jolbox.bonecp.ConnectionHandle.getMetaData(ConnectionHandle.java:814)
    at io.opentracing.contrib.spring.cloud.jdbc.JdbcAspect.getConnection(JdbcAspect.java:43)
    at sun.reflect.GeneratedMethodAccessor104.invoke
...
(126 additional frame(s) were not displayed)

CannotGetJdbcConnectionException: Failed to acquire connection for virtual shard 0 for get_alert_definitions_by_team_and_tag; nested exception is org.postgresql.util.PSQLException: This connection has been closed.
    at de.zalando.sprocwrapper.proxy.StoredProcedure.execute(StoredProcedure.java:440)
    at de.zalando.sprocwrapper.proxy.SProcProxy.handleInvocation(SProcProxy.java:53)
    at com.google.common.reflect.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:84)
    at com.sun.proxy.$Proxy100.getAlertDefinitionsByTeamAndTag
    at org.zalando.zmon.service.impl.AlertServiceImpl.getActiveAlertDefinitionByTeamAndTag(AlertServiceImpl.java:512)
...
(111 additional frame(s) were not displayed)

Failed to acquire connection for virtual shard 0 for get_alert_definitions_by_team_and_tag; nested exception is org.postgresql.util.PSQLException: This connection has been closed.
```

**Comment by vibhory2j** [comment]
Test issue created via sentry
